on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e v1.0. The matched version must equal to package version.

name: NPM publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 

      - run: npm ci  
      - run: npm run build:dts
        run: cd ./dist/
        
      - uses: peaceiris/actions-gh-pages@v3
      - run: npm publish || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}



